import re
import furst_instrument_paper
from ._export_figures import figures_latex

__all__ = [
    "section",
]

label = "sec:opticalPerformance"
"""The label of the section, for the manuscript to refer to."""


def _prose() -> str:
    """
    The text of the section, with every number written as a macro.

    The macros are defined at the top of the exported file, so the text
    follows the instrument model rather than drifting from it.
    """
    return r"""
\subsection{Optical Performance}
\label{sec:opticalPerformance}

The performance of the optical design was evaluated by tracing rays through
an idealized model of the instrument built with the open-source
\href{https://optika.readthedocs.io}{\texttt{optika}} raytracing package
\citep{optika}.
The model is shown in Figure~\ref{fig:layout}.
It places the \NumChannelsWords\ feed optics, the grating, and the detector
at their design positions on the Rowland circle.
The grating has a radius of curvature of \GratingRadius\ and a ruling density
of \GratingRulingDensity, so the Rowland circle has a radius of
\RowlandRadius.
The Sun is the field stop of the system and the grating is its pupil stop:
the field of view is the solar disk at its largest apparent size, and every
ray leaving a point on the disk is directed at a point on the clear aperture
of the grating, which is \GratingWidthClear\ wide and \GratingHeightClear\
tall.
Each feed optic is a convex cylinder of radius \FeedOpticRadius\ whose clear
aperture subtends \FeedOpticSubtent\ of the cylinder and is \FeedOpticHeight\
tall.

The feed optics illuminate the grating at angles of incidence from
\AngleIncidenceMin\ to \AngleIncidenceMax, and the detector lies
\AngleDiffraction\ from the grating normal on the same side, so that the
shortest wavelengths are observed close to the Littrow configuration.
Each channel therefore places a band about \ChannelBandwidth\ wide on the
detector, and the \NumChannelsWords\ bands together cover \WavelengthMin\ to
\WavelengthMax, with adjacent channels overlapping by at least
\ChannelOverlap\ so that the spectrum can be stitched together.
The dispersion at the detector is \DispersionPerPixel\ per pixel.

Since the virtual image of the entire Sun formed by a feed optic is
narrower than a pixel, the quantity that governs the spectral resolution is
the disk-integrated line spread function (LSF): the distribution along the
dispersion direction of the light from the whole solar disk and the whole
pupil at a single wavelength.
We compute it by tracing \NumWavelengthTraced\ wavelengths spanning the
detector in each channel, with the solar disk sampled by a stratified random
grid of \NumFieldSamples\ points and the pupil by one of \NumPupilSamples\
points.
The result is shown in Figure~\ref{fig:lsf}: the image of the Sun at each
wavelength is a line about a pixel wide, taller than the detector, and its
profile along the dispersion direction is roughly Gaussian.
We take the width of the LSF to be the standard deviation along the
dispersion direction of the positions of the rays reaching the detector,
added in quadrature with the standard deviation of a uniform distribution
one pixel wide, to account for the finite size of the pixels.
This width is shown in the top panel of Figure~\ref{fig:resolvingPower} and
ranges from \LsfWidthMin\ to \LsfWidthMax\ pixels.
It grows toward the long-wavelength channels, whose feed optics sit farthest
from the axis of the instrument, as the aberrations of the spherical grating
grow with the angle of incidence.

The resolving power, taken as the wavelength divided by twice the width of
the LSF, is shown in the bottom panel of Figure~\ref{fig:resolvingPower}.
It ranges from \ResolvingPowerMin\ to \ResolvingPowerMax\ over the traced
wavelengths, with a mean of \ResolvingPowerMean, and so exceeds the
requirement of \ensuremath{2 \times 10^4} throughout the bandpass.
"""


def section() -> str:
    """
    The LaTeX of the optical performance section, ready to be included in
    the manuscript with ``\\input``.

    The file defines a macro for every number it cites, then gives the text
    of the section, then the figures it refers to.
    """
    variables = [v.dumps() for v in furst_instrument_paper.variables()]

    parts = [
        "% Generated by furst-instrument-paper. Do not edit by hand.",
        "",
        "\n".join(variables),
        "",
        _prose().strip("\n"),
        "",
        figures_latex(),
    ]
    return "\n".join(parts) + "\n"


def _names_defined(latex: str) -> set[str]:
    """The names of the macros a piece of LaTeX defines."""
    return set(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}", latex))


def macros_undefined(latex: str) -> set[str]:
    """
    The macros a piece of LaTeX cites without defining.

    Used by the tests to make sure the text does not refer to a number the
    model has not supplied. Only capitalized names are checked, which is how
    every variable of this package is named and how no LaTeX primitive is.
    """
    defined = _names_defined(latex)
    cited = set(re.findall(r"\\([A-Z][A-Za-z]+)", latex))
    return cited - defined
