import matplotlib

matplotlib.use("agg")

import furst_instrument_paper
from furst_instrument_paper import _section


def test_section():
    result = furst_instrument_paper.section()
    assert isinstance(result, str)
    assert result.startswith("% Generated by furst-instrument-paper")
    assert r"\subsection{Optical Performance}" in result
    assert r"\begin{figure*}" in result
    assert r"\begin{figure}" in result


def test_macros_defined():
    """Every macro the prose cites is defined at the top of the file."""
    result = furst_instrument_paper.section()
    missing = _section.macros_undefined(result)
    assert not missing, f"undefined macros: {sorted(missing)}"
