import matplotlib

matplotlib.use("agg")

import furst_instrument_paper
from furst_instrument_paper import _section


def test_section():
    result = furst_instrument_paper.section()
    assert isinstance(result, str)
    assert result.startswith("% Generated by furst-instrument-paper")
    assert r"\subsection{Optical Performance}" in result
    assert r"\label{tab:designParameters}" in result
    assert r"\begin{figure*}" in result
    assert r"\begin{figure}" in result


def test_section_response():
    result = furst_instrument_paper.section_response()
    assert isinstance(result, str)
    assert result.startswith("% Generated by furst-instrument-paper")
    assert r"\subsection{Response}" in result
    assert r"\label{sec:response}" in result
    assert r"\label{tab:throughput}" in result
    assert r"\label{fig:response}" in result


def test_macros_defined():
    """Every macro the prose cites is defined at the top of its own file."""
    for result in [
        furst_instrument_paper.section(),
        furst_instrument_paper.section_response(),
    ]:
        missing = _section.macros_undefined(result)
        assert not missing, f"undefined macros: {sorted(missing)}"
